
SELECT R.CONTEST_ID, ROUND(COUNT(R.USER_ID)/(SELECT COUNT(USER_ID) FROM USERS)*100,2) AS PERCENTAGE
FROM REGISTER R
RIGHT JOIN USERS U ON R.USER_ID = U.USER_ID
WHERE R.CONTEST_ID IS NOT NULL
GROUP BY R.CONTEST_ID
ORDER BY PERCENTAGE DESC, CONTEST_ID ASC;
