SELECT Q.QUERY_NAME, ROUND(AVG(Q.RATING/Q.POSITION),2) AS QUALITY,
ROUND((SELECT COUNT(RATING) FROM QUERIES WHERE RATING<3 AND QUERY_NAME=Q.QUERY_NAME)/COUNT(Q.RATING)*100,2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES Q
GROUP BY Q.QUERY_NAME;
